### ISSUE TITLE
Latest version is missing from GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [glyphr-studio/Glyphr-Studio-Desktop#40]
The latest version is missing from GitHub Releases.

https://twitter.com/app4soft/status/1127573782317752320

**Comment by Autre31415** [comment]
[0.5.1 has been released](https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases/tag/v0.5.1)

**Comment by probonopd** [comment]
It says on the homepage: "Version 1 is here!"

**Comment by kethinov** [comment]
The desktop version uses a separate versioning system. 0.5.1 of the desktop app bundles v1.13.00 of Glyphr Studio.

**Comment by probonopd** [comment]
Uh, complicated...

**Comment by kethinov** [comment]
It's because they are technically two different projects that are updated independently. There are—for instance—features/bugs that are exclusive to the desktop app that the pure web version isn't concerned with. This is common to many projects that have both a web and desktop version, e.g. [Mattermost](https://mattermost.com/).
