### ISSUE TITLE
App crashe after few minutes usage

### ISSUE THREAD

**Issue by etshy** [glyphr-studio/Glyphr-Studio-Desktop#48]
Got a crash problem.
I passed few minutes creating a component and then use it to edit an existing font.
but after few minutes (about 10-20 minutes) the app entirely freeze and I can't do anything.

**Comment by kethinov** [comment]
Let me know if this is still an issue in the [latest version](https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases). If it is, detail specific steps to reproduce it, as I wasn't able to reproduce.

**Comment by somethingSTRANGE** [comment]
I'm running Glyphr Studio Desktop 1.13.10 on Windows 10 1902 (build 18363.959).

The application canvas (entire UI) goes white after 10 minutes or so while I'm editing a glyph. Only the menu bar "File Edit View Window Help" remains visible. I can't seem to close the application at this point using the "X" in the upper-right corner of the window, and must instead use Task Manager to kill the process.

I'm not sure if this is the same issue the original reporter had experienced. If necessary, I'll open a new issue. Otherwise, I'll update this issue if I gather any more information on what might cause the hang.

**Comment by shancarter963** [comment]
I have just discovered Glyphr Studio, and I love it!  But I am also having issues with it.  There seems to be a memory leak in both the desktop and online versions that cause them to crash.  I have learned to save my work frequently...  :)  

I am using Glyphr Studio Desktop 1.13.10 on Windows 10 Home version 20H2 (OS build 19042.867, 64-bit, with the "Windows Feature Experience Pack 120.2212.551.0"). I was also using the online version on Google Chrome (Version 89.0.4389.114 (Official Build) (64-bit)). 

To troubleshoot this, I kept Task Manager open while editing my font, and noticed that the memory allocation continually kept rising as I continued to edit my glyphs. It happened whether I saved frequently or not, although I didn't test whether it happened faster one way or another.

I can't find any log files to submit, but here's the font file I was working on.  Hope it helps you find the issue...

[St Patrick Font.gsf.txt](https://github.com/glyphr-studio/Glyphr-Studio-Desktop/files/6305876/St.Patrick.Font.gsf.txt)

**Comment by endervad** [comment]
I'd like to echo this issue since it's still not resolved. Both online, and desktop versions crash after some usage due to memory overflow (in online version the browser will specifically tell you that the page has run out of memory). I don't even feel like I'm doing anything too advanced, I'm just moving points around and modifying glyphs' width.

The most annoying thing is that it can happen while saving the project. So ideally you have to save after every glyph, and after 5-10 min in case of desktop version it's a good idea to restart Glyphr, or in case of online version - to re-open the project in a new tab. Otherwise saving will eventually crash the program/tab thus losing your progress. I can also confirm that it's visible from Task Manager how memory usage of Glyphr gradually goes only up.

Here's the project I'm working on. Not sure if it matters but initially I imported TTF file.
[Miedinger Med RUS - Glyphr Project.zip](https://github.com/glyphr-studio/Glyphr-Studio-Desktop/files/9372171/Miedinger.Med.RUS.-.Glyphr.Project.zip)

**Comment by Autre31415** [comment]
I was unable to reproduce this in https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases/tag/v0.6.0

Feel free to reopen if this bug is witnessed again.
